server {
    listen 80;

    # Serve Angular static files
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # Proxy API calls to NestJS
    location /api/ {
        proxy_pass http://nestjs-api:3000; # Use this if your NestJS API is running in a Docker container named 'nestjs-api'
        # proxy_pass http://host.docker.internal:3000/; # Use this if your NestJS API is running on your local machine (outside of Docker)
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}
